### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by ofer-dev** [niclabs/dtc#4]
Hey,
I just found about this project and it's really cool.
However, I've noticed no license is specified in the project repository, so it's unclear which uses are allowed.
Because it's a library I would recommend mit/bsd/apache/mozilla/lgpl so it's can be reused in other project without affecting their licensing.
Also, the following related project lack licenses.
https://github.com/niclabs/dtcnode
https://github.com/niclabs/dtcconfig
https://github.com/niclabs/dns-tools

Thanks

**Comment by jans23** [comment]
Any feedback would be much appreciated.

**Comment by madestro** [comment]
we are working on it, there are patents involved so it is an issue solved on lawyers-times

**Comment by ansiwen** [comment]
> we are working on it, there are patents involved so it is an issue solved on lawyers-times

@madestro Great, thanks for the reply!

FWIW, for now we specifically would be only interested in re-using the boilerplate code for binding the cryptoki API into a Go module for our own open source PKCS#11 module, so the DTC related code we would remove anyway. So it would already be very helpful for us if you would put the non-DTC code parts under a strict FLOSS license (like GPL etc.) for now, if that is something you could do more easily.

**Comment by jans23** [comment]
> we are working on it, there are patents involved so it is an issue solved on lawyers-times

Copyright and patents are separate matters. Technically you could publish source code as open source full of patents (and vice versa).

**Comment by madestro** [comment]
done in #b2891dd
