### ISSUE TITLE
Bad config file name in Network example

### ISSUE THREAD

**Issue by huguei** [niclabs/dtc#5]
Hi, just to let you know of an error for config filenames for dtcnodes on the Network-example wiki page. It says "/etc/dtcnode/config.yaml", but gives the error:

> panic: config file not found! Config File "dtcnode-config" Not Found in "[/etc/dtcnode /home/xxx]"
> 
> goroutine 1 [running]:
> main.main()
>         /usr/local/dtcnode/main.go:22 +0x1ed

Renaming it to dtcnode-config.yaml works.

Thanks.

**Comment by eriverosr** [comment]
You are right. I [just edited](https://github.com/niclabs/dtc/wiki/Create-Configurations) the wiki to clarify the names for each config file (client and nodes). I appreciate if you can check it and tell us if now is more understandable or not.

**Comment by huguei** [comment]
Yes, thanks! Looks good now.
